[package]
name = "jogo_de_adivinhação"
version = "0.1.0"
edition = "2021"
authors = ["Bruno de Sousa <sousasilvabruno97@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.3.14"